---
lab_3_tests:
  stage: test
  image: gitlab.cs.wallawalla.edu:5050/cs_department/docker-images/cpp
  script:
    - apt update
    - apt install -y flex bison
    - bison --version
    - cd lab-3
    - echo "Lab 3 - Flex"
    - flex -o scanner.c scanner.flex
    - echo "Lab 3 - Compile Tests"
    - gcc main_test.c scanner.c -o scanner_test.out
    - echo "Lab 3 - Run Tests"
    - ./scanner_test.out

lab_4_tests:
  stage: test
  image: gitlab.cs.wallawalla.edu:5050/cs_department/docker-images/cpp
  script:
    - apt update
    - apt install -y flex bison
    - bison --version
    - cd lab-4
    - echo "Lab 4 - Bison Parser"
    - make test
    - ./parser_test.out
