typedef enum {
  TOKEN_EOF = 0,
  TOKEN_IDENTIFICATION,
  TOKEN_KEYWORD_DIVISION,
  TOKEN_PROGRAM_ID,
  TOKEN_PROCEDURE,
  TOKEN_DISPLAY,
  TOKEN_STOP,
  TOKEN_RUN,
  TOKEN_STRING,
  TOKEN_DOT
} token_t;